### ISSUE TITLE
403 https://api2.realtor.ca/Listing.svc/PropertySearch_Post

### ISSUE THREAD

**Issue by sabatale** [rachitt96/pyRealtor#2]
Hello,

It looks like realtor.ca recently changed the https://api2.realtor.ca/Listing.svc/PropertySearch_Post endpoint.

All requests now result in 403.

**Comment by rachitt96** [comment]
Hi @sabatale ,

Thanks for using pyRealtor and raising a concern. 

Yes, we were getting 403 status code from Realtor.ca. After debugging, I found that their API Endpoint is same (https://api2.realtor.ca/Listing.svc/PropertySearch_Post), however they changed some of their API security features and started to block all API requests coming from proxy server.

I have changed the code, and published the new change in **pyRealtor** version **0.1.7**.

Could you please try reinstalling the package and running the code again?

**Comment by sabatale** [comment]
Thanks! Looks like it's working 👍
